server:
  port: 8100

spring:
  datasource:
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: token-service

eureka:
  client:
    availability-zones:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

logging:
  level:
    org.hibernate.type: TRACE
