server:
  port: 8100

logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:info}

spring:
  datasource:
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: token-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
